// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKCa3T2vfNLn_ZKJGGkM7OXBkx_VUcPNM',
    appId: '1:678736982232:web:84041b7172c7fbe90c27ad',
    messagingSenderId: '678736982232',
    projectId: 'sign-in-page-4b6bb',
    authDomain: 'sign-in-page-4b6bb.firebaseapp.com',
    storageBucket: 'sign-in-page-4b6bb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZy0H2XuidIrBe8sWmGQvKO26Q8Qpe9Os',
    appId: '1:678736982232:android:60d88cbd7ed85f2d0c27ad',
    messagingSenderId: '678736982232',
    projectId: 'sign-in-page-4b6bb',
    storageBucket: 'sign-in-page-4b6bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh-rbJlJQwsbkxmzmv9zTuBlwRZ53UraA',
    appId: '1:678736982232:ios:7bdfad5fb1f7d63c0c27ad',
    messagingSenderId: '678736982232',
    projectId: 'sign-in-page-4b6bb',
    storageBucket: 'sign-in-page-4b6bb.firebasestorage.app',
    iosBundleId: 'com.example.firebasePractice1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh-rbJlJQwsbkxmzmv9zTuBlwRZ53UraA',
    appId: '1:678736982232:ios:7bdfad5fb1f7d63c0c27ad',
    messagingSenderId: '678736982232',
    projectId: 'sign-in-page-4b6bb',
    storageBucket: 'sign-in-page-4b6bb.firebasestorage.app',
    iosBundleId: 'com.example.firebasePractice1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKCa3T2vfNLn_ZKJGGkM7OXBkx_VUcPNM',
    appId: '1:678736982232:web:1b2b26bad6d3d60b0c27ad',
    messagingSenderId: '678736982232',
    projectId: 'sign-in-page-4b6bb',
    authDomain: 'sign-in-page-4b6bb.firebaseapp.com',
    storageBucket: 'sign-in-page-4b6bb.firebasestorage.app',
  );
}
